### ISSUE TITLE
live streaming?

### ISSUE THREAD

**Issue by nybbs2003** [fabslab/aurora-websocket#5]
Hello!

I have experimented with your code for live streaming live generated audio (synthesized on demand in realtime). However, when playing in web browser, the audio stops sooner or later, and never get resumed automatically. It there ant way to get it back playing when more data is pushed to the client?

Thanks!

**Comment by DeusExLibris** [comment]
I know this is an old thread, but since I ran into this same issue, I thought I would respond.

The situation occurs because the player tries to get another chunk of audio data and it isn't available.  Specifically, you can look in the aurora player.coffee file, line 154.  I worked around this by adding a checkQueue function that calls device.start() when there is data in the buffer again.  I call this function every 100msec until there is data.

Unfortunately, this leads to choppiness in the decoded audio as the AV.AudioDevice starts and stops.

I suspect that this has something to do with aurora not having a duration for the audio, but I am not sure and haven't been able to work around the issue yet.  If I figure it out, I will post the solution back here in case you or anyone else wants to implement it.

**Comment by nybbs2003** [comment]
Thanks! I used custom websocket streaming instead.

**Comment by fabslab** [comment]
Feel free to share your custom streaming solution here if you'd like.
